server:
  port: 8080
spring:
  application:
    name: waa-project
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/waa
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true